version: "3"
services:
  db:
    image: postgres
    container_name: postgres_projekt_r
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: gsadmin
    volumes:
      - ./gsadmin.sql:/docker-entrypoint-initdb.d/gsadmin.sql:ro


